# Generated by Django 5.0.2 on 2024-09-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_file', models.FileField(upload_to='job_files')),
                ('job_description', models.TextField(blank=True, null=True)),
                ('template_image', models.FileField(blank=True, null=True, upload_to='template_images')),
            ],
        ),
    ]
